/* Step 1: using axios, send a GET request to the following URL 
           (replacing the palceholder with your Github name):
           https://api.github.com/users/<your name>
*/

/* Step 2: Inspect and study the data coming back, this is YOUR 
   github info! You will need to understand the structure of this 
   data in order to use it to build your component function 

   Skip to Step 3.
*/

/* Step 4: Pass the data received from Github into your function, 
           create a new component and add it to the DOM as a child of .cards
*/

/* Step 5: Now that you have your own card getting added to the DOM, either 
          follow this link in your browser https://api.github.com/users/<Your github name>/followers 
          , manually find some other users' github handles, or use the list found 
          at the bottom of the page. Get at least 5 different Github usernames and add them as
          Individual strings to the friendsArray below.
          
          Using that array, iterate over it, requesting data for each user, creating a new card for each
          user, and adding that card to the DOM.
*/

const followersArray = [];

/* Step 3: Create a function that accepts a single object as its only argument,
          Using DOM methods and properties, create a component that will return the following DOM element:

<div class="card">
  <img src={image url of user} />
  <div class="card-info">
    <h3 class="name">{users name}</h3>
    <p class="username">{users user name}</p>
    <p>Location: {users location}</p>
    <p>Profile:  
      <a href={address to users github page}>{address to users github page}</a>
    </p>
    <p>Followers: {users followers count}</p>
    <p>Following: {users following count}</p>
    <p>Bio: {users bio}</p>
  </div>
</div>

*/

/* List of LS Instructors Github username's: 
  tetondan
  dustinmyers
  justsml
  luishrd
  bigknell
*/

const newElement = (args) => {
  console.log(args);
  const element = document.createElement(args.type);
  element.textContent = args.text || '';
  element.classList.add(args.class || 'autogenerated');
  return element;
}

const cardCreator = (userObj) => {
  const userData = userObj.data;
  console.log(JSON.stringify(userData.name));

  const cardSection = newElement({type: 'div', class: 'card'});

  const topImg = newElement({type: 'img'});
  topImg.src = `${userData.avatar_url || userData.gravatar_id}`;
  cardSection.appendChild(topImg);

  const infoSection = newElement({type: 'div', class: 'card-info'});
  cardSection.appendChild(infoSection);

  const nameHeader = newElement({type: 'h3', class: 'name', text: `${userData.name !== null ? userData.name : userData.login}`});
  infoSection.appendChild(nameHeader);

  const username = newElement({type: 'p', class: 'username', text: `${userData.login}`});
  infoSection.appendChild(username);

  const location = newElement({type: 'p', text: `${userData.location}`});
  infoSection.appendChild(location);

  const profile = newElement({type: 'p', text: 'Profile: '});
  const profileLink = newElement({type: 'a', text: `${userData.html_url}`});
  profileLink.href = `${userData.html_url}`;
  profile.appendChild(profileLink);
  infoSection.appendChild(profile);

  const followers = newElement({type: 'p', text: `Followers: ${userData.followers}`});
  infoSection.appendChild(followers);

  const following = newElement({type: 'p', text: `Following: ${userData.following}`});
  infoSection.appendChild(following);

  return cardSection;
}

axios.get('https://api.github.com/users/Joshua-Burleson').then(user => {
  document.querySelector('.cards').appendChild(cardCreator(user));

})
.then(() => {
  axios.get('https://api.github.com/users/dustinmyers/followers').then(followers => {
    console.log(JSON.stringify(followers.data));
    followers.data.slice(0,5).forEach(follower => {
      axios.get(follower.url).then(followerData => {
        document.querySelector('.cards').appendChild(cardCreator(followerData));
      });
    });
  });
});